[package]
name = "base64_type"
authors = [ "IronCore Labs <code@ironcorelabs.com>" ]
version = "0.1.0"
edition = "2018"

[dependencies]
base64 = "0.13"
base64-serde = "0.6"
bytes = "1"
serde = "1"

[dev-dependencies]
proptest = "1.0"
proptest-derive = "0.3"
serde_json = "1"
