[package]
name = "base64_type"
authors = [ "IronCore Labs <code@ironcorelabs.com>" ]
version = "0.1.0"
edition = "2018"
resolver = "2"

[dependencies]
base64 = "0.13"
base64-serde = "0.6"
bytes = "1"
proptest = { version = "1.0", optional = true }
proptest-derive = { version = "0.3", optional = true }
serde = "1"

[dev-dependencies]
proptest = "1.0" 
proptest-derive = "0.3"
serde_json = "1"

[features]
arbitrary = [ "proptest", "proptest-derive" ]